spring:
  application:
    name: CLOUD-CONFIG-CLIENT
    
# DATA SOURCE SETTING
datasource:
    host: localhost
    port: 3309
spring:
  datasource:
    database: farmdeals
    password: p@55word@#
    url: jdbc:mysql://${datasource.host}:${datasource.port}/${datasource.database}?useSSL=false&serverTimezone=UTC
    username: root
    password: ${datasource.password}

# Hibernate properties
jpa:
    hibernate:
      ddl-auto: update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JPA properties
spring.jpa.show=true
spring.jpa.properties.hibernate.format_sql=true
