spring:
  application:
    name: CLOUD-CONFIG-CLIENT
    startup:
        message: ${spring.application.name} is up and running on port number ${server.port}
datasource:
    database: farmdeals
    host: localhost
    port: 3309
spring:
    datasource:
        password: p@55word@#
        url: jdbc:mysql://${datasource.host}:${datasource.port}/${datasource.database}?useSSL=false&serverTimezone=UTC
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show: true
